GET http://localhost:5000/api/users


###

GET http://localhost:5000/api/users/5ec17e49c8afc1310e1d8731

###

POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
  "email": "zaazz@zzz.zz",
  "password": "zzzzzz"
}

###

DELETE http://localhost:5000/api/users/5ec02dba34431b291455d1a5

###

PATCH http://localhost:5000/api/users/5ec17e49c8afc1310e1d8731
Content-Type: application/json

{
  "age": 16
}